export const rowData = [
  {
    id: 1,
    title: "Car",
    price: 10,
    company: "Toyota",
    info: "One of the best Car",
    inCart: false,
    count: 1,
  },
  {
    id: 2,
    title: "Bike",
    price: 20,
    company: "Honda",
    info: "Good Bike",
    inCart: false,
    count: 1,
  },
  {
    id: 3,
    title: "Book",
    price: 50,
    company: "Book Angecies",
    info: "Nice Book To Read",
    inCart: false,
    count: 1,
  },
  {
    id: 4,
    title: "Cycles",
    price: 60,
    company: "Frog",
    info: "Best for health",
    inCart: false,
    count: 1,
  },
  {
    id: 5,
    title: "TV",
    price: 50,
    company: "LG",
    info: "Nice clarity",
    inCart: false,
    count: 1,
  },
  {
    id: 6,
    title: "Computer",
    price: 60,
    company: "Honda",
    info: "Help to do programs",
    inCart: false,
    count: 1,
  },
  {
    id: 7,
    title: "Laptop",
    img: "img/car7.jpg",
    price: 50,
    company: "Lenovo",
    info: "Good to do multitasking",
    inCart: false,
    count: 1,
  },
];
